apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: quikscribe
  labels:
    app: quikscribe-backend

data:
  DEBUG: "true"
  FRONTEND_ALLOWED_ORIGINS: "http://localhost:3000"
  FRONTEND_URL: "http://localhost:3000"
  DOCKER_IMAGE_NAME: "meeting-bot"
