apiVersion: v1
kind: Service
metadata:
  name: quikscribe-backend-svc
  namespace: quikscribe
  labels:
    app: quikscribe-backend
spec:
  selector:
    app: quikscribe-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
